### ISSUE TITLE
Step 2. Login and Configure the CLI shows conflicting messages to user

### ISSUE THREAD

**Issue by riazvm** [jetstack/jsctl#42] opened 2022-10-15 02:09 UTC
jsctl auth login
redirects me to the browser, i use my jetstack email - the browser displays a message Unauthorized, where as the terminal shows Login succeeded. User gets two conflicting messages

**Comment by charlieegan3** [comment] 2022-10-20 10:30
I'm not able to replicate this. Are you making sure that you're using the correct google account in your browser?

**Comment by charlieegan3** [comment] 2022-11-01 11:39
I'm closing this as a dupe of https://github.com/jetstack/jsctl/issues/51. Feel free to re-open if you have issues after the next release.

**Closed by charlieegan3** 2022-11-01 11:39 UTC
